### PR TITLE
Localize

### PR DESCRIPTION
**Pull request by abenrob**
Several things of note:
- Full app dir re-org, as all pages need to be includes to avoid repetition for each language, and each lang's content is in a dir by it's tag (i.e. 'en')
- Site URL's defined in frontmatter, not directory structure now. This eases the work for adding a new language (files have sensical names now, not just index within dirs)
- Site rebuilt to support fr, but translation not at all complete for fr (really only navbar...)
- I18n gem used to support localization of dates. travis will need updating, and any dev will need to ```bundle install``` &/or ```bundle update``` to continue
- different languages treat numbering differently. For example, in English, we would say November 1st, 2nd,etc. for dates. In French, we would say le 1,2,3, Novembre. Localization of dates doesn't go to this extreme, so date for events presented as number only, to ease translation date oddities.
- adding translations requires 3 steps, which I will outline in the translation [issue thread](https://github.com/MissingMaps/missingmaps.github.io/issues/45) and README (of this branch) once merged

### CODE REVIEW

**Comment by abenrob** [comment]
There are a few small publish branch commits that were not integrated into this PR, as the codebase is drastically different, and merges could not be done automatically. Once stable, we should tag those items as issues, and fix manually based on the PR code. The CSV event load was integrated, as it was a pretty big deal, but some of the smaller ones were not.

**Comment by dalekunce** [comment]
@abenrob can you list all the changes that were missed I would like to be able to automatically merge this branch. Happy to work on it as well to get this pushed this week.

**Comment by abenrob** [comment]
@dalekunce I went through each commit and either pulled changes in, or verified update had already been made.Remaining issues are:
- figure out landing page svg translation
- document process for adding language (I will do shortly)
- get translations in place - FR has structure in place but needs content translated, other languages will need full process
- mobile nav language links (I will also do shortly)

**Comment by dalekunce** [comment]
@DylanMoriarty can you help with the svg fix?

**Comment by abenrob** [comment]
#125 trumps this PR, and includes all the merge error resolutions.

**Pull request closed without merging**
