### PR TITLE
FR translation for header and landing content

### PR DESCRIPTION
**Pull request by Eleonore9**
* FR translation for the header content and landing content paragraphs (not complete).
* Also fixed a typo in the EN version.
* Decided to use the term "cartopartie" as a translation of mapathon as seen on [OSM France website](https://openstreetmap.fr/tags/cartopartie).
* Added quotes around terms in English like "Missing Maps". I guess it's not indispensable. Also I had to use single quotes so as not to break the yml file.

### CODE REVIEW

**Comment by dalekunce** [comment]
This looks great. I think we won't quote missing maps though. Can you remove the quotes and we are happy to merge. 

Thanks for the great work.

**Comment by Eleonore9** [comment]
I removed the quotes! Thanks @dalekunce!

**Comment by mnoblecourt** [comment]
@Eleonore9 sorry coming a bit late but the consensus on the French community is now to use "mapathon" for remote mapping activities like Missing maps (same than in English), and "cartopartie" for field mapping activities (walking papers, OSMTracker... translation of "mapping party").

**Comment by Eleonore9** [comment]
Ok, @mnoblecourt. I can change that (later today)!

**Comment by abenrob** [comment]
I am PRing (#147) the full fr translations as prepared by @smehenni and @tsamaya.
It is current with publish branch commits. Best path would be to wait until we deploy localization branch to publish, and make PRs against that once live.

**Comment by Eleonore9** [comment]
Ok. I'm closing this PR, then!

**Pull request closed without merging**
