### PR TITLE
foundation-sites version bump

### PR DESCRIPTION
**Pull request by dalekunce**

### CODE REVIEW

**Comment by dalekunce** [comment]
@danbjoseph please review and merge

**Comment by danbjoseph** [comment]
i think the [_settings.scss](http://foundation.zurb.com/sites/docs/sass.html#the-settings-file) file is usually the place to make customizations to the default foundation styles. when you removed the one that was there and imported the one from the foundation-sites folder download, did you lose anything specific to the MM site? (although the callout note in the docs makes it sound like a settings file for an old version doesn't usually cleanly transition up)

**Comment by danbjoseph** [comment]
do we really need to keep all the foundation files in the repo? does compass allow you to look in multiple directories for your sass files? it seems that`gulp-sass` lets you look in multiple directories with an `includePaths` option as discussed in this [stackoverflow](http://stackoverflow.com/a/33588202) and shown [here](https://github.com/danbjoseph/user-auth/blob/master/gulpfile.js#L7)

**Comment by danbjoseph** [comment]
done differently in #311

**Pull request closed without merging**
