### PR TITLE
Trainingpage

### PR DESCRIPTION
**Pull request by cljohn**
I have drafted a page to go between the "map" button on the homepage, and the task manager.
This includes some basic training videos for beginners.
Let me know if you have any suggestions for improving this.

Thanks
Claire

### CODE REVIEW

**Comment by dalekunce** [comment]
Overall I love this idea. There are a few things that need to be cleaned up before I can merge it in. Great work I really appreciate it.

- the link on the homepage should be to "*.html" not "#*.html"
- rename link to "contribute.html" as we are planning to do other things with "map.html"
- remove empty <h2 /> tags
- remove globe icons from buttons in the start mapping section
- need different backgrounds for the start mapping and beginners sections
- call to action to map now should be more prominent

**Comment by cljohn** [comment]
Updated based on Dale's feedback.

**Comment by danbjoseph** [comment]
hey, what's the source for learn.png, mapLink.png, and extraTraining.jpg?

**Comment by cljohn** [comment]
One of the graphic designers in my office put it together.

**Pull request merged**
