### PR TITLE
Update events.csv

### PR DESCRIPTION
**Pull request by pedrito1414**
Added London event

### CODE REVIEW

**Comment by danbjoseph** [comment]
the new entry has a date of "8/4/2015"
should be "9/1/2015"?

**Comment by pedrito1414** [comment]
Yes. Sorry Dan. Been a bit of a week!

**Comment by danbjoseph** [comment]
the eventbrite for the added event has "ended" for all the ticket categories.
not sure if that means it's full or there's some sort of error?

**Comment by danbjoseph** [comment]
the eventbrite for the added event has "ended" for all the ticket categories.
not sure if that means it's full or there's some sort of error?

**Pull request merged**
