### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by dalekunce**

### CODE REVIEW

**Comment by dalekunce** [comment]
@abenrob there seem to be some conflicts can you resolve these. I have limited connection at the moment traveling.

**Comment by abenrob** [comment]
Conflicts resolved, new PR directly to publish branch: #150. Can close this PR.

**Comment by abenrob** [comment]
#152 has been successfully merged with publish on local branches, should make this PR pass once accepted.
attn @dalekunce @smit1678 @nbumbarger

**Comment by DylanMoriarty** [comment]
screenshot 2016-03-23 09 44 17

This is a considerable amount of text for an introduction. I'm all for being more specific on what MM is, but it pushes down the 'Get Involved' considerably and isn't very engaging. I think cutting it down to a variation of the last line,

>Missing Maps is an open, collaborative project in which you can help to map areas where humanitarian organisations are trying to meet the needs of vulnerable people.

would make for a stronger landing page. Alternatively, you could keep the original one,

>Missing Maps is powered by OpenStreetMap volunteers around the world and in your community who map far off places and their own neighborhoods.

and add this to a block between the landing view & How We Work graphic.

**Comment by abenrob** [comment]
@DylanMoriarty that text was updated by @pedrito1414 in #133 (which was folded into my localization changesets)

**Comment by smit1678** [comment]
I tested this locally quick. Everything looks good with a couple items that would probably be good to hit before we merge: 

  - [ ] S'IMPLIQUER link on FR at top switches back to EN 
  - [ ] using rgb(0,0,0) on the process section headers, probably should keep consistent with current live site grey
  - [ ] should fix language switcher on subpages so it doesn't reset to homepage. would help with usability between versions. 

On the landing page text, @DylanMoriarty @pedrito1414 yeah it may be worth paring it down slightly to make it a bit more readable. I typically only skim these type of subheader paragraphs regardless of length and look more at the action items first but may be useful to be a little shorter for readability. 

I can help take a look at the checklist later today but wanted to flag here now.

**Comment by abenrob** [comment]
I can do the S'IMPLIQUER one.
Not sure how best to do the language switcher one, as languages have different names for the links, so it 's not just swap the lang code...

**Comment by dalekunce** [comment]
+1 @DylanMoriarty that is way way to much text above the fold. @pedrito1414 can you trim that down before we merge.

**Comment by smit1678** [comment]
Ok last items in https://github.com/MissingMaps/missingmaps.github.io/pull/148#issuecomment-200422633 were fixed and merged into this branch. Real-time stats are also added to this branch #151. Only remaining item is the landing page text. Once that is fixed it looks like we are good to go. 

@dalekunce @pedrito1414 - will let you both make the last call on the edits and when ready to go live. 

cc @abenrob @DylanMoriarty @nbumbarger

**Comment by abenrob** [comment]
:+1:

**Comment by dalekunce** [comment]
Merging now and I'll work with @pedrito1414 to clean up the welcome text.

**Pull request merged**
