### PR TITLE
update french translation

### PR DESCRIPTION
**Pull request by ViolaineCartONG**
french translation branch ready to be merged

### CODE REVIEW

**Comment by abenrob** [comment]
Looks like the in-progress spanish translation work got mixed into the french updates. We'll need to remove the es commits and should be good to go. cc @ViolaineCartONG

**Comment by ViolaineCartONG** [comment]
@abenrob Arg, thats totally the thing to do, so sorry, not yet fully at ease with this system..

**Comment by abenrob** [comment]
@dalekunce anyone able/willing to bring this in ?

**Comment by danbjoseph** [comment]
looks like a system file `.fr.yml.swp` got mixed up in this?
if so, should probably be removed. but went ahead and merged this.

**Comment by ViolaineCartONG** [comment]
@danbjoseph thanks for your help!

**Pull request merged**
