### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by imbaah**
Adding the new logo here to replace the logo in the header. Will do a pull request to delete the old one after.

### CODE REVIEW

**Comment by imbaah** [comment]
I do not want to delete the current logo in this branch as it is used as a source for the logo present in the website's header. I want to add this file so I can use it as a source to change the header logo. I will delete the old logo once the new one is in the header of the website. Thank you.

**Comment by danbjoseph** [comment]
the edits on your fork of the repository and an associated pull request will not affect the website until the pull request is merged. you can make the complete update (add files, remove files, edit code) all in one pull request.

**Comment by imbaah** [comment]
Tried to follow your request.

**Comment by danbjoseph** [comment]
yes, thank you, looking good. we will also need to check that the deleted logo files are not used in other places on the website (that is, outside of the header).

**Pull request merged**
