### PR TITLE
Update en.yml

### PR DESCRIPTION
**Pull request by pedrito1414**
text updated in ENG

### CODE REVIEW

**Comment by abenrob** [comment]
@pedrito1414 @dalekunce should we do a pause and review content here? I'm doing translations, and if we have major text changes like this to come, I need to stop and wait...

**Comment by pedrito1414** [comment]
Aplogies, @abenrob tried to get the edits in as quick as I could. 

I'm done with the homepage for now. So, I think you're ok to continue...

Maybe @harry-wood might want to review the HOT donate messaging just in case, but I think it's ok...

**Comment by harry-wood** [comment]
looks good to me

**Comment by abenrob** [comment]
Pas de soucis Pete. Good thing you're looking at it now, and not after we have a half-dozen translations in place!

**Comment by dalekunce** [comment]
+1 @pedrito1414 @abenrob 

Can we get this cleaned up so it will auto merge into the localization branch

**Comment by pedrito1414** [comment]
@dalekunce I think we're done on the copy for the home page

**Comment by abenrob** [comment]
The text from this PR have been folded into my last PR. We should be good to close this.

**Pull request closed without merging**
