### PR TITLE
Adds realtime stats

### PR DESCRIPTION
**Pull request by nbumbarger**
##### To be merged with localization branch.
Adds a connection to the MissingMaps API for summary statistics shown on the landing page (users, total edits, building additions, road km additions). The current running totals are added to a snapshot of the totals from before we started collecting stats. To quote the explanation in the script:

> Note: MissingMap began collecting statistics in real-time beginning February 16, 2016, a few of which are displayed on the MissingMaps landing page (users, total edits, building edits, and road kilometer additions). The object below contains a summary of the number of edits in these categories that were submitted prior to February 16, 2016, which are added to the running total to estimate totals going back to 2014. Users are calculated in realtime by the current API, so no additions are necessary.

cc @dalekunce, @smit1678

### CODE REVIEW

**Comment by abenrob** [comment]
I just submitted #150 which resolves all conflicts between localization and publish, and essentially makes it deploy ready. So you could: 
- PR to my [publish branch](https://github.com/abenrob/missingmaps.github.io) which is merged with the localization changesets. That way I can merge your commits, and they will be pulled in with the PR resolution OR
- wait until #150 is accepted, and PR again to the updated MM publish branch

Thoughts?

**Comment by smit1678** [comment]
@abenrob I'm thinking that if the major updates are not ready to be deployed yet, the ideal situation is to have you merge your fork back into `localization` since this has become the main new feature branch. Jumping ahead and merging straight to `publish` from your fork may not be the best method since we have an active feature branch from that main new branch. That way we can both be we're prepping and working off of the same branch that can be merged when everyone is ready to push it live. 

There are a couple of strings that need to be translated on `add-realtime-stats` branch before it can be added anyways so it may be good practice to keep localization up to date before everything goes live. 

I also noticed a couple of design and spacing items that would be ideal to be fixed before we merge `localization`.

**Comment by abenrob** [comment]
@smit1678 fine by me. @dalekunce asked me to fix conflicts between localization and publish in his attempted PR to publish (#148), but it seemed (to me) to be counterproductive to PR to a branch with a pending PR...  Is there someone in the missing maps repo team that can prioritize and expedite PRs? Seems like getting localization and publish merged sooner than later is going to be helpful (in light of the level of changes between the branches...) I'll close #150, and open a new PR to localization, but would be good to have a timeline for the merge.

**Comment by smit1678** [comment]
thanks @abenrob. #152 merged. @nbumbarger Tested this locally and this looks good. Will flag the string translations in #148.

**Pull request merged**
