### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by abenrob**
Closes #120 - this is mergeable.

### CODE REVIEW

**Comment by abenrob** [comment]
Travis build will need updating ...

**Comment by dalekunce** [comment]
@adenrob what in travis needs to be updated.

**Comment by abenrob** [comment]
Assuming the addition of the I18n gem.

**Comment by abenrob** [comment]
@dalekunce @DylanMoriarty I remade the svgs to use text instead of outlines, and used them as \_includes so we can insert the localized text. I combined the three steps into one svg template for the mobile view, as it is easier to manage that way.

**Comment by DylanMoriarty** [comment]
This is some really great work @abenrob. Thanks!

Checking it out there's a few quirks in the styling from the changes. Will fix/flag any issues I come across.

**Comment by abenrob** [comment]
Coolio. Let's get this merged into the mm/localization branch so we can work on it there. I have some help lined up for translation completion, but it will be easier for them to PR against mm, and not my branch.

**Comment by DylanMoriarty** [comment]
@abenrob merged into localization here. 

From what I can tell, there might be a few issues that from the translations throwing some of the spacings off- you can currently see this in the fr header where the paragraph breaks down a line when the window width is reduced.

https://github.com/MissingMaps/missingmaps.github.io/tree/localization

**Comment by abenrob** [comment]
@DylanMoriarty I see what you mean. We should widen the break point for the collapsed menu. I doubt french will even be the widest navbar... I bet german is longer still. It looks ok with a breakpoint of 650, and I could imagine 700 even, to accommodate longer ones. I'll update that, but as a new PR. Closing this one, so I can keep current with localization head.

**Pull request closed without merging**
